name: Build app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build packages for aarch64
      run: |
        cd env-packages
        for i in $(ls packages); do ./build-package.sh -a aarch64 $i; done

    - name: Build packages for arm
      run: |
        cd env-packages
        for i in $(ls packages); do ./build-package.sh -a arm $i; done

    - name: Build packages for i686
      run: |
        cd env-packages
        for i in $(ls packages); do ./build-package.sh -a i686 $i; done

    - name: Build packages for x86_64
      run: <
        cd env-packages
        for i in $(ls packages); do ./build-package.sh -a x86_64 $i; done
        
    - name: Build app with Gradle
      run: |
        cd alpine-term-app
        chmod +x gradlew
        ./gradlew build
